# Site settings
title: Dudmy's Blog
description: A homebody trying to survive as a developer.
cover: "/assets/cover.jpeg"
logo: "/assets/logo.png"

# Author
name: Dudmy
email: dudmy@dudmy.net

# Gem settings
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
highlightjs_theme: "monokai-sublime"

# Disqus comments
disqus_shortname: dudmysblog

# Google analytics
ga_tracking_id: "UA-65643570-2"