highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://dudmy.github.io
author: dudmy

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl:
title: Dudmy's Resume
name: Jung Yujin
email: dudmy@dudmy.net
email_full: mailto:dudmy@dudmy.net
website: Blog
website_full: http://blog.dudmy.net/
github: dudmy
linkedin: dudmy
slideshare: dudmy
google_analytics: UA-65643570-2

# needed for travis-ci build
exclude: [vendor]
