#
###################################
# Site wide configuration
####################################
#
title: Dudmy's Blog
description: A blog to strive to survive as a developer.
url: http://dudmy.github.io
keywords: ["Programming", "Android", "Java", "Kotlin"]

#
###################################
# Jekyll configuration
####################################
#
markdown: kramdown
highlighter: rouge
permalink: pretty

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

plugins: [jekyll-sitemap, jekyll-seo-tag]

#
###################################
# Author configuration
####################################
#
author:
  name: Dudmy
  avatar: logo.png
  email: dudmy@dudmy.net
  job: "Android Developer"
  bio: "An android developer who does not like to come out of bed."

#
###################################
# Social configuration
####################################
#
resume: https://github.com/dudmy/resume
disqus-shortname: dudmysblog
facebook: #username
github: dudmy #username
linkedin: dudmy #username
instagram: #username
google-analytics: UA-65643570-2
