# Permalinks
permalink:          pretty

# Setup
title:              Dudmy's blog
tagline:            'Funny n Happy'
description:        'Life is C between B and D'
url:                http://dudmy.github.io
baseurl:            ''

# About/contact
author:
  name:             Dudmy
  email:            dudmy@dudmy.net

# Social link
github:             https://github.com/dudmy

# Gems
gems:               [jekyll-paginate, jekyll-sitemap, jekyll-seo-tag]
paginate:           5
paginate_path:      "page:num"

# Custom vars
version:             1.0.0

# Etc
google-analytics:   UA-65643570-2
