# Site settings
title: Dudmy's Devprint
title_ko: 더드미의 개발자국
description: Lazy programmer powered by Caffeine. Turn coffee into < code />.
cover: "/assets/cover.png"

# Author
name: Dudmy
email: dudmy@dudmy.net

# Gem settings
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Build settings
markdown: kramdown
permalink: pretty
paginate: 10
paginate_path: "/page:num/"
highlightjs_theme: "hybrid"

# Disqus comments
disqus_shortname: dudmysblog

# Google analytics
ga_tracking_id: "UA-65643570-2"
